# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_identification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identification',
            name='file',
            field=models.FileField(upload_to='id_documents/'),
        ),
    ]
