# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180309_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('housing_expense', models.DecimalField(decimal_places=2, max_digits=12)),
                ('time_in_europe', models.IntegerField()),
                ('has_bank_account', models.BooleanField(default=False)),
                ('amount_in_bank', models.DecimalField(decimal_places=2, max_digits=12)),
                ('has_cash', models.BooleanField(default=False)),
                ('amount_cash', models.DecimalField(decimal_places=2, max_digits=12)),
                ('has_debts', models.BooleanField(default=False)),
                ('amount_debts', models.DecimalField(decimal_places=2, max_digits=12)),
                ('missed_payments', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='profile_photo',
            field=models.FileField(null=True, upload_to='profile_photos/'),
        ),
        migrations.AddField(
            model_name='employment',
            name='paystub',
            field=models.FileField(null=True, upload_to='paystubs/'),
        ),
    ]
