# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180309_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='country',
            field=models.CharField(choices=[('italy', 'Italy'), ('france', 'France'), ('germany', 'Germany')], default='italy', max_length=256),
            preserve_default=False,
        ),
    ]
