# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_account_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialinfo',
            name='amount_cash',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='amount_debts',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='amount_in_bank',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='housing_expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='missed_payments',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='monthly_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
