# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180309_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='paystub',
            field=models.FileField(blank=True, null=True, upload_to='paystubs/'),
        ),
    ]
