# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180309_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialinfo',
            name='account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Account'),
            preserve_default=False,
        ),
    ]
