# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_financialinfo_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employment',
            name='wage',
        ),
        migrations.AddField(
            model_name='employment',
            name='monthly_salary',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=6, verbose_name='Monthly Salary'),
            preserve_default=False,
        ),
    ]
