# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180309_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialinfo',
            name='has_cash',
        ),
        migrations.AddField(
            model_name='financialinfo',
            name='loan_file',
            field=models.FileField(blank=True, null=True, upload_to='loan_docs/'),
        ),
        migrations.AddField(
            model_name='financialinfo',
            name='num_months_debt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialinfo',
            name='ongoing_debt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financialinfo',
            name='reason_ongoing',
            field=models.CharField(choices=[('health', 'Health'), ('lost_job', 'Lost Job'), ('migration_issues', 'Migration Issues'), ('other', 'Other')], default=' ', max_length=256),
            preserve_default=False,
        ),
    ]
