# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20180309_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialinfo',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Account'),
        ),
        migrations.AlterField(
            model_name='identification',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Account'),
        ),
    ]
