# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20180309_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='credit_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='country',
            field=models.CharField(choices=[('Italy', 'Italy'), ('France', 'France'), ('Germany', 'Germany')], max_length=256),
        ),
    ]
