# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 22:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20180309_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('code', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('leaser_name', models.CharField(max_length=256)),
                ('leaser_email', models.CharField(max_length=256)),
                ('guaranter_name', models.CharField(max_length=256)),
                ('guranter_email', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='has_lease',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='amount_debts',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='missed_payments',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='num_months_debt',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='reason_ongoing',
            field=models.CharField(blank=True, choices=[('health', 'Health'), ('lost_job', 'Lost Job'), ('migration_issues', 'Migration Issues'), ('other', 'Other')], max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Account'),
        ),
        migrations.AddField(
            model_name='lease',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Group'),
        ),
    ]
