# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-10 02:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20180309_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lease',
            name='guaranter_name',
        ),
        migrations.RemoveField(
            model_name='lease',
            name='guranter_email',
        ),
        migrations.AddField(
            model_name='lease',
            name='duration',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='lease',
            name='guarantor_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='gurantor_email',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='payments_made',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='lease',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Group'),
        ),
    ]
