# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-10 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20180310_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='applied_for_lease',
            field=models.BooleanField(default=False),
        ),
    ]
