# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-10 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_account_applied_for_lease'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='name',
        ),
        migrations.AlterField(
            model_name='employment',
            name='monthly_salary',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monthly Salary'),
        ),
    ]
