# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-10 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20180310_0346'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='months_left_in_current_job',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='amount_cash',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
