# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-10 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20180310_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
