# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-10 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_lease_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='risk_profile_string',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
